/*
Project Euler, Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

#include <iostream>

using namespace std;

int main ()
{
	int sum = 2;
	int first = 1; 
	int second = 2;
	int current = 0;

	while (current < 4000000)
	{
		current = first + second;
		if (current % 2 == 0)
		{
			sum += current;
		}
		
		first = second;
		second = current;
	}
	cout << sum << "\n";
}
